apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  MONGO_DB: {{ .Values.config.mongoDatabase | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  CLIENT_URLS: {{ .Values.config.clientUrls | quote }}