apiVersion: v1
kind: Service
metadata:
  name: streaming-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP

  selector:
    app: streaming

  ports:
    - name: http
      port: 3002
      targetPort: 3002